### ISSUE TITLE
TravisCI Integration

### ISSUE THREAD

**Issue by traviskaufman** [traviskaufman/bencode-rs#5]
``` yaml
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
```
